development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7cc06eef076ef0b0c20d35f790c530df@pike.redistogo.com:9323/
  channel_prefix: sockets_messenger_backend_production
